#!/usr/bin/env bash
# Build libdcimgui.a for linux-aarch64. Uses aarch64-linux-gnu-g++ (Debian:
# `apt install g++-aarch64-linux-gnu`). Run on x86-64 to cross-compile, or
# natively on an aarch64 Linux host (in which case the regular `c++` works too).
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
IMGUI="$REPO/vendor/imgui"
GEN="$REPO/c3imgui.c3l/generated"
OUT_DIR="$REPO/c3imgui.c3l/linked-libs/linux-aarch64"
BUILD="$REPO/build/linux-aarch64"
PLATFORM="linux-aarch64"

mkdir -p "$OUT_DIR" "$BUILD"

CXX="${CXX:-aarch64-linux-gnu-g++}"
AR="${AR:-aarch64-linux-gnu-ar}"
if ! command -v "$CXX" >/dev/null 2>&1; then
    echo "error: $CXX not found. On Debian/Ubuntu install via:"
    echo "  apt install g++-aarch64-linux-gnu"
    echo "Or set CXX=<your-aarch64-c++>."
    exit 1
fi

# /usr/aarch64-linux-gnu/include is Debian's multiarch sysroot for aarch64.
SDL_INC="${SDL_INC:-/usr/aarch64-linux-gnu/include}"
CXXFLAGS=(
    -O2 -fPIC -fno-exceptions -fno-rtti -fno-threadsafe-statics
    -I"$IMGUI" -I"$IMGUI/backends" -I"$GEN" -I"$SDL_INC"
)

source "$REPO/c3imgui.c3l/scripts/common/build_common.sh"

SOURCES=("${CORE_SOURCES[@]}")
BUNDLED_LIBS=()
# Optional backend probe only fires meaningfully when the aarch64 sysroot is at
# a discoverable location. Skip on cross-builds — consumers can rerun the build
# script on a native aarch64 host where /usr/include is the real header tree.
if [[ "${PROBE_OPTIONAL:-0}" == "1" ]]; then
    common_optional_linux_backends
fi

ar_build_archive
# No layout probe — can't run aarch64 binary on x86-64 host. The sizes.json
# generated by build_linux_x64.sh is reused; struct layouts match across
# any LP64 ABI ImGui supports.

echo
echo "consumers must also link: -lstdc++ -lSDL3 -lGL -lm  (on aarch64)"
